fredbet:
  image: fred4jupiter/fredbet
  links:
    - mongodb
  ports:
    - "8180:8080"
  environment:
   - spring.profiles.active=test,demodata

mongo1:
  hostname: mongo1
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
  restart: always

mongo2:
  hostname: mongo3
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27018:27017"
    - "28018:28017"
  restart: always

mongo3:
  hostname: mongo2
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27019:27017"
    - "28019:28017"
  restart: always
 
