cache:
  directories:
  - "$HOME/.m2/repository"
sudo: required
services:
  - docker
language: java
jdk:
- oraclejdk9
install:
- mvn verify
deploy:
  provider: heroku
  api_key:
    secure: NjeYQvzkSJPW6cNXQxhblhMyC7zJOJ/Kl8wpC2G6CM8Wkco2GUdHvErutgfpJbCygUS3cN1PU0D2QROm87RCZVZ0/wb/Cv4K1tz04tGD552Z7tDUv8OCZEjY2cntSD2DJOCjvcmvgjv/fAg+n2RlxiJFu81qOEBi+xgrechGk4IOog8QVgJSEToOthn6riDi3U2nASCYlfpJrwIF17Wc/F7JanSrk7uNwdKGsdnCCOS4nx9D57rj3jZuKS9EPL68PF/n3ZYTk+C7zLZNhVs1erPkjailozBnLM8IYNfZZSAb4ZMEB5ErZVPts3NKbzvXtoO/UamBaM32mRnKfsOnxh3c8a3qr0TJm5GIQrwev5J/ufPFow+CfF65BHdezl6VBXjql2w4bvWE0D1vnpgeNlXKjXLGsJMLrr/fngMMKz7QwoXmWnrQr6EcQi3aYnxqgq6+rJfpkeWuK6GnE/+G8beeiYJPPJCAa9U2Jrpd/FFi1piL3N+1XPRa6wTOqyGSyMUb5eGqu0eEEKdO2w44XDUEWEeoLlYUmN63hlv0mmAHLOe+vMxrQGnbwYFvU5j23kJnyNI17DWKFVHw0zEd2bAS442DYlkixjtrCWn+pbPBKD89ZzU4W4BDlo55ygdZK9MFN31NyxA/qh7GROelWGl6AyxnpqkUO+NIfDls5qg=
# safelist
branches:
  only:
  - master
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t fred4jupiter/fredbet .  
  - docker tag fred4jupiter/fredbet fred4jupiter/fredbet:latest  
  - docker push fred4jupiter/fredbet:latest