sudo: required
services:
  - docker
before_install:
  - docker build -t fred4jupiter/fredbet .
  - docker tag fred4jupiter/fredbet fred4jupiter/fredbet:latest
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push fred4jupiter/fredbet:latest
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN
branches:
  only:
  - master
cache:
  directories:
    ~/docker