fredbet:
  image: fred4jupiter/fredbet
  links:
    - mongodb:mongodb
  ports:
    - "80:8080"
 
mongodb:
  image: mongo
  volumes:
  - /var/lib/mongodb:/data/db 
  ports:
  - "28017:28017"
  expose:
  - "27017"
  - "28017"
