version: '3'

services:
    mysqldb:  
      image: mysql:8.0.2
      ports:
        - "3306:3306"
      environment:
       - MYSQL_DATABASE=fredbetdb
       - MYSQL_ROOT_PASSWORD=secred
       - MYSQL_USER=fred
       - MYSQL_PASSWORD=fred
    fredbet:
      image: hamsterhase/fredbet:latest
      links:
        - mysqldb
      depends_on:
        - mysqldb
      ports:
        - "8081:8080"
      environment:
       - SPRING_PROFILES_ACTIVE=prod
       - FREDBET_DATABASE_URL=jdbc:mysql://mysqldb:3306/fredbetdb
       - FREDBET_DATABASE_USERNAME=fred
       - FREDBET_DATABASE_PASSWORD=fred
       - FREDBET_DATABASE_TYPE=mysql
