spring:
  thymeleaf:
    cache: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:h2:mem:fredbetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-changelog.xml
  h2:
    console:
      enabled: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
  jmx:
    enabled: false

# metrics configuration
management:
#  server:
#    port: 5555
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      enabled: true

# -------- fredbet properties ------------------------------------------------------------------------------

fredbet:
  image-size: 1920
  thumbnail-size: 75
  image-location: file_system
  # set folder where you want to store images to (defaults to user home dir)
  image-file-system-base-folder:
  aws-s3bucket-name: fredbet
  aws-access-key:
  aws-secret-key:
  aws-region: eu-central-1
  default-language: de
  create-demo-data: false

# -------- user groups and permissions ------------------------------------------------------------------------------

fredbet-user-groups:
  groups:
    - groupName: ROLE_USER
      permissions:
    - groupName: ROLE_USER_ENTER_RESULTS
      permissions:
        - PERM_EDIT_MATCH_RESULT
    - groupName: ROLE_SUB_ADMIN
      permissions:
        - PERM_EDIT_MATCH
        - PERM_EDIT_MATCH_RESULT
        - PERM_CREATE_USER
        - PERM_USER_ADMINISTRATION
        - PERM_PASSWORD_RESET
        - PERM_EDIT_USER
        - PERM_EDIT_INFOS_RULES
        - PERM_EDIT_INFOS_PRICES
    - groupName: ROLE_ADMIN
      permissions:
        - PERM_CREATE_MATCH
        - PERM_EDIT_MATCH
        - PERM_EDIT_MATCH_RESULT
        - PERM_DELETE_MATCH
        - PERM_CREATE_USER
        - PERM_EDIT_USER
        - PERM_DELETE_USER
        - PERM_PASSWORD_RESET
        - PERM_USER_ADMINISTRATION
        - PERM_SYSTEM_INFO
        - PERM_ADMINISTRATION
        - PERM_CHANGE_USER_ROLE
        - PERM_EDIT_INFOS_RULES
        - PERM_EDIT_INFOS_PRICES
        - PERM_SHOW_ACTIVE_USERS
        - PERM_SHOW_LAST_LOGINS
        - PERM_EDIT_IMAGE_GROUP
        - PERM_DOWNLOAD_IMAGES
        - PERM_DELETE_ALL_IMAGES