# override properties of defaults settings in application.yml here
spring:
  thymeleaf:
    cache: false
  h2:
    console:
      # connect in console (http://localhost:8080/console) with jdbcUrl: jdbc:h2:mem:testdb
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  datasource:
    hikari:
      # jdbc-url: jdbc:h2:file:~/fredbet/fredbetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      jdbc-url: jdbc:h2:mem:fredbetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/fredbet
#      username: fredbet
#      password: fredbet
#      driver-class-name: com.mysql.jdbc.Driver