spring:
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: file:src/main/resources/static
      cache:
        period: 0
  h2:
    console:
      # connect in console (http://localhost:8080/h2)
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:~/fredbetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

logging:
  pattern:
    console: "%highlight(%d %-5level [%c] - %msg%n)"
  level:
    de.fred4jupiter.fredbet: DEBUG

fredbet:
  create-demo-data: false