dockerui:
  image: dockerui/dockerui
  privileged: true
  ports:
  - "9000:9000"
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock

fredbet:
  image: fred4jupiter/fredbet
  ports:
    - "8080:8080"
  environment:
   - spring.profiles.active=dev,demodata
 
