mongodata:  
  image: mongo:3.0.6
  volumes:
    - /data/db
  command: --break-mongo

mongodb:  
  image: mongo:3.0.6
  volumes_from:
    - mongodata
  ports:
    - "27017:27017"
  command: --smallfiles

fredbet:
  image: fred4jupiter/fredbet
  links:
    - mongodb
  ports:
    - "8080:8080"
  environment:
   - spring.profiles.active=mongodbsingle
