mariadb:  
  image: mariadb:10.1.11
  volumes:
    - /data/db
  ports:
    - "3306:3306"
  environment:
   - MYSQL_DATABASE=fredbetdb
   - MYSQL_ROOT_PASSWORD=secred
   - MYSQL_USER=fred
   - MYSQL_PASSWORD=fred
