version: "3"
services:
    postgres:  
      image: postgres
      volumes:
        - ~/pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
       - POSTGRES_USER=fred
       - POSTGRES_PASSWORD=fred
       - POSTGRES_DB=fredbetdb
    fredbet:
      image: fred4jupiter/fredbet
      links:
        - postgres
      depends_on:
        - postgres
      ports:
        - "8080:8080"
      environment:
       - SPRING_PROFILES_ACTIVE=prod
       - SPRING_DATASOURCE_HIKARI_JDBC_URL=jdbc:postgresql://postgres:5432/fredbetdb
       - SPRING_DATASOURCE_HIKARI_USERNAME=fred
       - SPRING_DATASOURCE_HIKARI_PASSWORD=fred
       - SPRING_DATASOURCE_HIKARI_DRIVER_CLASS_NAME=org.postgresql.Driver
