name: Build and Publish Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      run: docker build -t fred4jupiter/fredbet .
    - name: Publish to Docker Hub
      run: docker push fred4jupiter/fredbet
      with:
        name: fred4jupiter/fredbet
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true