name: Docker Hub
on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16 for deploy to Docker Hub
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          server-id: docker.io
          server-username: ${{ secrets.DOCKER_USERNAME }}
          server-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Docker Hub
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build -Dimage=docker.io/fred4jupiter/fredbet
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}