name: Publish to GitHub Container Registry
on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16 for deploy to GitHub Container Registry
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          server-id: ghcr.io

      - name: Publish to GitHub Container Registry
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build -Dimage=ghcr.io/fred4jupiter/fredbet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}