name: Publish Docker latest image
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B verify
  build_push_ghcr_amd64:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up JDK 17 for deploy to GitHub Container Registry
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          server-id: ghcr.io
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Publish to GitHub Container Registry
        run: mvn -B compile jib:build -Dimage=ghcr.io/fred4jupiter/fredbet:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  build_push_docker_hub_amd64:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v3
#      - name: Set up JDK 17 for deploy to Docker Hub
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '17'
#          server-id: docker.io
#      - name: Cache local Maven repository
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_TOKEN }}
#      - name: Publish to Docker Hub
#        run: mvn -B compile jib:build -Dimage=docker.io/fred4jupiter/fredbet:latest
  build_push_docker_hub_buildx:
    runs-on: ubuntu-18.04
    needs: build
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: fred4jupiter/fredbet
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
      - name: Docker Login
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
      - name: Build image with buildx
        if: success()
        run: |
          docker buildx build \
            --platform linux/arm64/v8,linux/amd64 \
            --tag ${{ steps.prepare.outputs.docker_image }}:latest \
            --tag ${{ steps.prepare.outputs.docker_image }}:latest \
            --file ./Dockerfile-buildx \
            --output type=image,push=true .