name: Publish Release
on:
  push:
    branches:
      - master
jobs:
  build_tag_repo:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{steps.version_update.outputs.release-version}} # use in jobs: ${{needs.build_tag_repo.outputs.release_version}}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B verify
      - name: Update to release version and tag
        id: version_update
        uses: fred4jupiter/maven-version-update-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print release version
        run: "echo 'New release Version: ${{steps.version_update.outputs.release-version}}'"
  build_push_ghcr_amd64:
    runs-on: ubuntu-latest
    needs: build_tag_repo
    steps:
      - name: Checkout the tagged code
        uses: actions/checkout@v3
        with:
          ref: ${{needs.build_tag_repo.outputs.release_version}}
      - name: Set up JDK 17 for deploy to GitHub Container Registry
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          server-id: ghcr.io
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Publish to GitHub Container Registry
        run: mvn -B compile jib:build -Dimage=ghcr.io/fred4jupiter/fredbet:${{needs.build_tag_repo.outputs.release_version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_push_docker_hub_amd64:
    runs-on: ubuntu-latest
    needs: build_tag_repo
    steps:
      - name: Checkout the tagged code
        uses: actions/checkout@v3
        with:
          ref: ${{needs.build_tag_repo.outputs.release_version}}
      - name: Set up JDK 17 for deploy to Docker Hub
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          server-id: docker.io
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish to Docker Hub
        run: mvn -B compile jib:build -Dimage=docker.io/fred4jupiter/fredbet:${{needs.build_tag_repo.outputs.release_version}}
  build_push_docker_hub_arm64:
    runs-on: ubuntu-18.04
    needs: build_tag_repo
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: fred4jupiter/fredbet
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_TARGET_PLATFORM: linux/arm64/v8
    steps:
      - name: Checkout the tagged code
        uses: actions/checkout@v3
        with:
          ref: ${{needs.build_tag_repo.outputs.release_version}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
          echo ::set-output name=version::${{needs.build_tag_repo.outputs.release_version}}-arm64
      - name: Docker Login
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
      - name: Run Buildx (push image)
        if: success()
        run: |
          docker buildx build \
            --platform ${{ steps.prepare.outputs.docker_platform }} \
            --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
            --file ./Dockerfile-arm \
            --output type=image,push=true .
  publish-github-release:
    runs-on: ubuntu-latest
    needs: build_tag_repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false