name: Publish Docker latest image
on:
  workflow_dispatch:
    inputs:
      release_tag_version:
        description: 'The release tag version number to use, e.g. 2.8.0'
        required: true
    branches:
      - master
jobs:
  build_push_ghcr_amd64:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17 for deploy to GitHub Container Registry
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          server-id: ghcr.io
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Publish to GitHub Container Registry
        run: mvn -B verify jib:dockerBuild -Dimage=ghcr.io/fred4jupiter/fredbet:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_push_docker_hub_amd64:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17 for deploy to Docker Hub
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          server-id: docker.io
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish to Docker Hub
        run: mvn -B verify jib:dockerBuild -Dimage=docker.io/fred4jupiter/fredbet:latest
  build_push_docker_hub_arm64:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push'
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: fred4jupiter/fredbet
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_TARGET_PLATFORM: linux/arm64/v8
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
          echo ::set-output name=version::latest-arm64
      - name: Docker Login
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
      - name: Run Buildx (push image)
        if: success()
        run: |
          docker buildx build \
            --platform ${{ steps.prepare.outputs.docker_platform }} \
            --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
            --file ./Dockerfile-arm \
            --output type=image,push=true .