version: "3.8"
services:
  traefik:
    image: traefik:v2.9
    container_name: "traefik"
    restart: always
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL_ADDRESS}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8180:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  fredbet:
    image: fred4jupiter/fredbet:latest
    container_name: "fredbet"
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fredbet.rule=Host(${DOMAIN_NAMES})"
      - "traefik.http.routers.fredbet.entrypoints=websecure"
      - "traefik.http.routers.fredbet.tls=true"
      - "traefik.http.routers.fredbet.tls.certresolver=letsencrypt"
      - "traefik.http.routers.fredbet.service=fredbet"
      - "traefik.http.services.fredbet.loadbalancer.server.port=8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
  postgres:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
  backup:
    image: eeshugerman/postgres-backup-s3:14
    environment:
      - SCHEDULE=@hourly
      - BACKUP_KEEP_DAYS=7     # optional
      - PASSPHRASE=${BACKUP_PASSPHRASE}
      - S3_REGION=eu-central-1
      - S3_BUCKET=${S3_BUCKET_NAME}
      - S3_PREFIX=backup
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      